from PIL import Image
import os

ICONS = {
    "icon_sun": "weather_sun",
    "icon_cloud_fog": "weather_cloud_fog",
    "icon_rain": "weather_rain",
    "icon_snow": "weather_snow",
    "icon_thunder": "weather_thunder",
}

ICONS_DIR = "icons"
OUT_FILE = "firmware/icons.h"

THRESHOLD = 128  # pixels darker than this become white on OLED

def png_to_bytes(path):
    img = Image.open(path)
    img = img.convert('RGBA')
    w, h = img.size

    if w != h:
        s = min(w, h)
        left = (w - s) // 2
        top = (h - s) // 2
        img = img.crop((left, top, left + s, top + s))
        w = h = s

    pixels = img.load()
    out = []
    for y in range(h):
        byte = 0
        for x in range(w):
            r, g, b, a = pixels[x, y]
            if a < 128:
                bit = 0  # transparent/background -> black on OLED
            else:
                lum = (r + g + b) // 3
                bit = 1 if lum < THRESHOLD else 0
            byte = (byte << 1) | bit
            if (x + 1) % 8 == 0:
                out.append(byte)
                byte = 0
        if w % 8 != 0:
            byte <<= (8 - (w % 8))
            out.append(byte)
    return out, w, h

def main():
    lines = []
    lines.append("/*")
    lines.append(" * icons.h - Weather icons bitmaps for SSD1306")
    lines.append(" * Auto-generated by convert_icons.py")
    lines.append(" */")
    lines.append("#ifndef ICONS_H")
    lines.append("#define ICONS_H")
    lines.append("")
    lines.append("#include <Arduino.h>")
    lines.append("")
    lines.append("// Small icon dimensions (16x16, used in weather text screen)")
    lines.append("#define ICON_WIDTH  16")
    lines.append("#define ICON_HEIGHT 16")
    lines.append("")

    for filename, array_name in ICONS.items():
        path = os.path.join(ICONS_DIR, f"{filename}.png")
        if not os.path.exists(path):
            print(f"WARNING: {path} not found, skipping")
            continue

        data, w, h = png_to_bytes(path)
        bytes_per_row = (w + 7) // 8
        lines.append(f"#define {array_name.upper()}_WIDTH {w}")
        lines.append(f"#define {array_name.upper()}_HEIGHT {h}")
        lines.append(f"const uint8_t {array_name}[{bytes_per_row} * {h}] PROGMEM = {{")
        row_bytes = []
        for i in range(0, len(data), bytes_per_row):
            row = data[i:i+bytes_per_row]
            row_bytes.append("  " + ", ".join(f"0x{b:02X}" for b in row))
        lines.append(",\n".join(row_bytes))
        lines.append("};")
        lines.append("")

    lines.append("#endif // ICONS_H")

    with open(OUT_FILE, "w") as f:
        f.write("\n".join(lines))

    print(f"Generated {OUT_FILE}")

if __name__ == "__main__":
    main()
